baseURL: http://gen3.org/
languageCode: en-us
title: Gen3.org
theme: hugo-fresh

params:
  hero:
    tagline: Gen3 is...
    subTagline: how data commons are made. Data commons co-locate data, storage and computing infrastructure with commonly used tools for analyzing and sharing data to create an open interoperable resource for the research community.
    why: Data commons speed up and democratize the process of scientific discovery enabling more scientific research through pragmatic access to vast data and computing resources.
    buttonText:
    - text: View on GitHub
      link: https://github.com/search?q=topic%3Agen3+org%3Auc-cdis&type=Repositories
    - text: Explore A Data Commons
      link: https://nci-crdc-demo.datacommons.io/
    image: illustrations/worker.svg
  demo:
    aname: demo
    tagline: Sandbox
    subTagline: Try out a Gen3 Data Commons sandbox with open access data so you can explore the search, download, and API capabilities.
    buttonText:
    - text: Explore A Data Commons
      link: https://nci-crdc-demo.datacommons.io/
    image: illustrations/app-mockup.png
  navbar:
    logo:
      src: logos/fresh.svg
      alt: Gen3 Data Commons Logo
  whygen3:
    aname: whygen3
    tagline: Why Gen3?
    points:
    - title: Flexible data model
      description: Gen3 supports a graph data model backed by a data dictionary. The data dictionary and data model are encoded into easy to edit YAML files.
      icon: dictionary.svg
    - title: Open source software
      description: Gen3 is built on a foundation of open source software including Python, Flask, Nginx, Apache, Kubernetes, Terraform, Packer, React, Jenkins, Go, Jupyter, PostgreSQL and Docker. Gen3 is itself open source under the Apache version 2.0 license.
      icon: opensource.png
    - title: Cloud Agnostic
      description: Gen3 currently supports Amazon Web Services, Google Cloud Platform, and Openstack environments with support soon for Microsoft Azure. Gen3 is capable of being run in these environments while securely handling controlled access data. Gen3 commons have been run in environments that are compliant with FISMA and FedRAMP moderate protocols.
      icon: cybersecurity.svg
  getstarted:
    aname: getstarted
    tagline: Get Started
    points:
    - title: I want to run a Gen3 commons
      description: Learn how to run a Gen3 data commons using either Docker-Compose or our Cloud Automation scripts. Docker-Compose lets you quick start your new data commons in a matter of minutes!
      icon: build
      text: Learn more about running Gen3
      link: /docs/runcommons/
      aname: runacommons
    - title: I want to submit data to a Gen3 commons
      description: Please read our generic user documentation on how to submit data to a Gen3 commons. To submit data to a specific commons, please see their documentation and be in touch with their support email. For your own data commons, feel free to modify our generic doucmentation.
      icon: submit
      text: Learn more about submitting data
      link: /docs/submitdata/
      aname: submitdata
    - title: I want to access data in a Gen3 commons
      description: Read the swagger docs on the Gen3 APIs and visit sample queries in our generic Gen3 user documentation. To obtain authorized access to protected data, please contact the support email for that data commons.
      icon: access
      text: Learn more about accessing data
      link: /docs/accessdata/
      aname: accessdata
    - title: I want to build an app for a Gen3 commons
      description: Build applications for Gen3 data commons using our REST & GraphQL APIs. Build the data exploration portal of your dreams, or build a custom way to submit specific data nodes. The power is yours!
      icon: buildapp
      text: Learn more about building apps
      link: /docs/buildapps/
      aname: buildapps
  moreinfo:
    aname: media
    tagline: Media
  services:
    aname: about
    tagline: Gen3 Services
    clientExamples:
    - position: Data Submission
      quote: Gen3 supports data submission including clinical attributes, phenotypic information, and data files. The submissions are validated against the data dictionary to ensure all required fields are present and have appropriate data values.
      image: sheepdog.png
    - position: Object Index
      quote: Gen3 provides permanent data GUIDs (globally unique IDs) for data objects. The service tracks the physical locations and hash of every asset (file) in the data commons object store. The Gen3 platform includes landing pages which support FAIR descriptions of the data objects.
      image: indexd.png
    - position: Data Search
      quote: Gen3 features a friendly GraphQL API for searching and discovering data. The GraphQL API enables faceted and precise searching through the flexible data model. Search capabilities enable quick and easy creation of virtual cohorts that can  be exported to a manifest for data download.
      image: peregrine.png
    clientExamples2:
    - position: AuthN/AuthZ
      quote: Gen3 utilizes OpenID Connect for providing AuthN services with AuthZ specified on a per commons basis. Currently supported identity providers include Google and Shibboleth, supporting providers such as NIH iTrust, InCommon Federation, and eduGAIN.
      image: fence.png
    - position: Data Portal
      quote: Gen3 includes a data portal as a default application over a commons. The portal is an interactive website that allows users to explore, submit, and download data. The data portal utilizes the public APIs offered by the data commons as a demonstration to the power of Gen3.
      image: windmill.png
    - position: API
      quote: All of the Gen3 services support powerful APIs which allow them to interact with each other and external users. These APIs enable extensible application development for future services and users.
      image: extra.png
  contributors:
    aname: contributors
    tagline: Contributors
    logos:
    - title: CDIS
      icon: cdis.svg
  footer:
    image: fresh-white.svg
    columns:
    - title: Gen3
      links:
      - name: About
        url: "#about"
      - name: Community
        url: "https://forums.gen3.org"
      - name: Why Gen3
        url: "#whygen3"
      - name: Demo
        url: "#demo"
      - name: Media
        url: "#media"
    - title: Get Started
      links:
      - name: Run a Gen3 commons
        url: "#runacommons"
      - name: Submit data to a commons
        url: "#submitdata"
      - name: Access data in a commons
        url: "#accessdata"
      - name: Build an app for Gen3
        url: "#buildapps"

menu:
  sectionmenu:
      - name: "About"
        url: "#about"
        identifier: "about"
        weight: 10

      - name: "Community"
        url: "https://forums.gen3.org"
        identifier: "community"
        weight: 11

      - name: "Why Gen3?"
        url: "#whygen3"
        identifier: "whygen3"
        weight: 20

      - name: "Demo"
        url: "#demo"
        identifier: "demo"
        weight: 21

      - name: "Get Started"
        url: "#getstarted"
        identifier: "getstarted"
        weight: 30

      - name: "I want to run a Gen3 commons"
        url: "#runacommons"
        parent: "getstarted"
        weight: 301

      - name: "I want to submit data to a Gen3 commons"
        url: "#submitdata"
        parent: "getstarted"
        weight: 302

      - name: "I want to access data in a Gen3 commons"
        url: "#accessdata"
        parent: "getstarted"
        weight: 303

      - name: "I want to build an app for a Gen3 commons"
        url: "#buildapps"
        parent: "getstarted"
        weight: 304

      - name: "Media"
        url: "#media"
        identifier: "media"
        weight: 40
